alias blu='bluetoothctl'
alias colors='xfce4-terminal --color-table'
alias df='df -h --total'
alias dirs='dirs -p -v'
alias du='du -h'
alias fknbt='sudo modprobe -r btusb; sudo modprobe btusb'
alias fknwifi='sudo service network-manager restart'
alias glo='git log --oneline -n 5'
alias has="dpkg --get-selections | grep -v deinstall | awk '{ print \$1 }' | grep -i"
alias hidebar='xdo above -t $(xdo id -n root) $(xdo id -a bar)'
alias linst='apt list --installed'
alias ls='ls -lh --color=auto'
alias pls='sudo $(fc -ln -1)'
alias py='python3'
alias todo='grep -n TODO: ./*'

