#! /bin/sh

# xrandr monitors
xrandr --output DP-1 --primary --mode 2560x1440
xrandr --output eDP-1 --auto --left-of DP-1 --mode 1400x900

# bspc monitors
# in this particular order so IX X come before I II III... in desktop list
bspc monitor eDP-1 -g 1400x900+0+0
bspc monitor eDP-1 -d IX X

bspc monitor DP-1  -g 2560x1440+1400+0
bspc monitor DP-1  -d I II III IV V VI VII VIII

# set wallpaper (but don't create ~/.fehbg file)
feh --nofehbg --bg-fill ~/Pictures/thelan_1920.jpg

# set local fonts
xset +fp ~/.local/share/fonts
xset fp rehash

# set default cursor to left pointer
# without this, the default X cursor is the 'x'
xsetroot -cursor_name left_ptr

# bspc windows
bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color \#859900
bspc config normal_border_color  \#002b36

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config click_to_focus any

# rules
bspc rule -a *:floatterm state=floating
bspc rule -a zoom desktop=IX

# launch hotkey manager
sxhkd &

# launch bar
~/rodbar.sh &
xdo above -t $(xdo id -n root) $(xdo id -a bar)

bspc config -m DP-1  top_padding  36
bspc config -m eDP-1 top_padding   0
