#! /bin/sh

# xrandr monitors
xrandr --output DP-1 --primary --mode 2560x1440
xrandr --output eDP-1 --auto --left-of DPI-1

# bspc monitors
# in this particular order so IX X come before I II III... in desktop list
bspc monitor eDP-1 -g 2160x1440+0+0
bspc monitor eDP-1 -d IX X

bspc monitor DP-1  -g 2560x1440+0+0
bspc monitor DP-1  -d I II III IV V VI VII VIII

# set wallpaper
feh --bg-fill ~/Pictures/thelan_1920.jpg

# set local fonts
xset +fp ~/.local/share/fonts
xset fp rehash

# bspc windows
bspc config border_width         4
bspc config window_gap          12

bspc config -m DP-1  top_padding  36
bspc config -m eDP-1 top_padding   0

bspc config focused_border_color \#859900
bspc config normal_border_color  \#002b36

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config click_to_focus button1

# rules
# TODO: don't think this does anything
bspc rule -a google-chrome state=tiled

# launch hotkey manager
sxhkd &

# launch bar
~/rodbar.sh &
